### PR TITLE
Fix two xpos tags which appear to be typos

### PR DESCRIPTION
**Pull request by AngledLuffa**

### CODE REVIEW

**Comment by AngledLuffa** [comment]
To ping regarding this - is it possible to get this included in 2.8?  If not, can we look at resolving it for the subsequent version?

**Comment by mr-martian** [comment]
No, past releases don't get changed. The soonest these changes could get released is version 2.10 in May.

**Comment by AngledLuffa** [comment]
That comment was a year old :/

**Comment by mr-martian** [comment]
Ah, I saw that there was recent activity and didn't register that some things weren't recent.

**Review by msimi — COMMENTED** [review]
I think the lemma should be lowercase for consistency. Only lemmas for proper nouns are upper case.

**Review by msimi — APPROVED** [review]

**Review by msimi — APPROVED** [review]

**Comment by AngledLuffa** [comment]
> I think the lemma should be lowercase for consistency. Only lemmas for proper nouns are upper case.

How about like this?

https://github.com/UniversalDependencies/UD_Italian-VIT/pull/2/commits/d7f5bd6233db565c071fb9c3fcde90f0425d2712

**Review by msimi — COMMENTED** [review]
I don't see why you should split 'Financiere'

**Comment by AngledLuffa** [comment]
It was `mw-Financière, mw-Moulinex` in three places in the original text.  Two of those places were split, and the third was unsplit as per the sentence I was changing here

**Review by msimi — COMMENTED** [review]
This sentence should be fixed. I think Financiere Moulinex is the correct version. (actually it should be Financière Moulinex).

**Review by msimi — COMMENTED** [review]
I think the correct version is Financiere.

**Review by msimi — COMMENTED** [review]
I think the correct version is Financiere.

**Review by msimi — APPROVED** [review]

**Review by msimi — APPROVED** [review]

**Review by msimi — APPROVED** [review]

**Comment by AngledLuffa** [comment]
So in all three cases it should be unsplit?  2002, 2009, 2010?

**Comment by msimi** [comment]
I don't have the original text. Is it consistently wrong?

**Comment by AngledLuffa** [comment]
It came up three times:

`art-la, mw-Financière, mw-Moulinex, npro-Dcsm, ...`
`sp-[part-nella, sn-[mw-Financière, mw-Moulinex, npro-Dcsm, punt-',', ...`
`spd-[partd-della, sn-[mw-Financière, mw-Moulinex, npro-Dcsm]]`

I don't know which is right or wrong (google search seems to suggest `Financière` with the diacritic) but consistency would be helpful.

I can fix these three sentences however we need - is there something else wrong with the PR that leads to it being closed?

**Comment by AngledLuffa** [comment]
Nevertheless, substitute "2.8" for "next release" and the desire to have
these small changes integrated so I don't have to keep using our git clone
is still there

**Pull request closed without merging**
